### ISSUE TITLE
Group Posts的recyclerview显示问题

### ISSUE THREAD

**Issue by SeakyLuo** [SeakyLuo/Moments#23]
![screenshot_2018-11-16-14-12-18](https://user-images.githubusercontent.com/25042708/48650343-921ebc00-e9aa-11e8-9681-33ea950d3376.png)
![screenshot_2018-11-16-14-11-59](https://user-images.githubusercontent.com/25042708/48650348-95b24300-e9aa-11e8-8608-5fcc25af26da.png)

顶部有空白，底部显示不全

**Comment by DennisZZH** [comment]
改了FrameLayout以后：
平板测试结果 1）顶部空白问题解决
                       2）底部显示不全问题 没有解决。 每次都是 最底部一条post的菜单栏被遮挡。

**Comment by DennisZZH** [comment]
issue addressed.
适当更改了FrameLayout的layout_height。 
原来被遮蔽的部分高度就是app bar的高度。现在将framelayout的layout height减少了app bar的高度，就可以显示了。layout_height = height(warp content) - height(app bar)。
