### ISSUE TITLE
在Drawer里上传头像

### ISSUE THREAD

**Issue by a211212abc** [SeakyLuo/Moments#25]
就不放在注册里了 这不是必须的步骤
建议用Firebase的Storage储存 然后存到Auth的PicURI里 我还没细看 就大概说说

**Comment by SeakyLuo** [comment]
得放注册里，但是只当一个占位的坑而已，可以放一个默认的头像，然后个人主页里可以改，但不会放在导航栏里

**Comment by SeakyLuo** [comment]
已经在个人主页里实现，就等你实现login然后上传了
