### ISSUE TITLE
在Firebase中上传bitmap

### ISSUE THREAD

**Issue by SeakyLuo** [SeakyLuo/Moments#29]
现在因为无法下载bitmap会导致GroupsFragment闪退
因为Firebase需要一个Bitmap()的constructor，但是Bitmap不提供
主要是为了上传用户头像跟群组头像
可能可以用Firebase Storage实现，可以利用用户头像跟群组头像当key
另外，我抄了一个不用Storage的就可以上传Bitmap函数在FirebaseHelper中，被comment了

**Comment by a211212abc** [comment]
在做了

**Comment by SeakyLuo** [comment]
还有下载
