### ISSUE TITLE
User Profile的scroll问题

### ISSUE THREAD

**Issue by SeakyLuo** [SeakyLuo/Moments#36]
NestedScrollView中有个SwipeFreshLayout，讲道理这个应该在NestedScrollView外面，但是放到外面之后会错位，请修复错位问题

**Comment by DennisZZH** [comment]
现在运行时user profile是空的

**Comment by DennisZZH** [comment]
貌似解决了。名片和post都能向上滚动。

**Comment by a211212abc** [comment]
问题无法复现，请具体说明
