### ISSUE TITLE
User Profile顶部Status bar

### ISSUE THREAD

**Issue by SeakyLuo** [SeakyLuo/Moments#4]
顶部status bar应该透明，跟图片放在下面一样，应该是`android:fitsSystemWindows="true"`的问题

![image](https://user-images.githubusercontent.com/25042708/48373500-db9f9c00-e676-11e8-8cc4-7c1d3d57e879.png)

**Comment by SeakyLuo** [comment]
![image](https://user-images.githubusercontent.com/25042708/48529903-29b8c900-e84a-11e8-886d-b95d702c0e6e.png)
现在只有折叠的时候有问题了，然后还多了一个新的bug，title没了

**Comment by SeakyLuo** [comment]
![image](https://user-images.githubusercontent.com/25042708/48535268-8bcff900-e85f-11e8-91ef-71b6ca5ad33e.png)
不知道为啥有奇怪的留白

**Comment by DennisZZH** [comment]
scroll 不改了。 暂时算完成。
